### ISSUE TITLE
Migrate to Github Pages

### ISSUE THREAD

**Issue by nashe** [securitywithoutborders/securitywithoutborders.github.io#5]
Right now, accessing the website at https://securitywithoutborders.github.io/ just shows the content of `README.md`—it's not really what's expected.

Github Pages works in two ways:
  - Create a project using Jekyll (not Middleman) and each commit on `master` will build & serve the website automatically. The results of the compilation doesn't have to be commit'ed.
  - Keep Middleman but create a pre-commit hook to compile the website and commit it to the `build` folder but in the branch `gh-pages`.

I really prefer the Jekyll option. This way, you don't need to install anything to be able to make small modifications of the website and publish it. It'll also keep the commit history clean, since you won't fill it with commits related to the compilation results. It won't take too much time to migrate the project to Jekyll.

Just tell me what do you prefer and I'll make a PR accordingly :-)

**Comment by Tethik** [comment]
We just made the switch to Middleman, so I doubt we'll change back to Jekyll just yet ;)

For now this repo and what comes out of it is served on the main securitywithoutborders.org website. I'm not sure if we intend to keep the site mirrored on the github.io domain. Doing so would also cause some issue with how the contact form works.

**Comment by nashe** [comment]
Oh, I thought that the main website was just mirroring the github.io one. So I guess we can close the issue now ;-)

**Comment by Tethik** [comment]
Yeah, we'll be renaming the repo shortly to avoid confusion.
