### ISSUE TITLE
Set ENV variable for contact form URL

### ISSUE THREAD

**Issue by eschaefer** [securitywithoutborders/securitywithoutborders.github.io#9]
I had hardcoded a contact form URL helper, which needs to be dynamic based on the environment in which the site is built for. Production probably doesn't want a `localhost` URL. 
https://github.com/securitywithoutborders/securitywithoutborders.github.io/blob/master/config.rb#L42

**Comment by Tethik** [comment]
Yes, please. This currently has to be edited manually during deploy.
